# This is a basic workflow to help you get started with Actions

name: markdownUrlTest

on:
  workflow_dispatch:
    inputs:
      tagname:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  preview-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: job summary
        run: |
          echo "### inputs" >> $GITHUB_STEP_SUMMARY
          echo "- tagname: [${{ github.event.inputs.tagname }}](https://github.com/haga-triple1/actions-trial/releases/tag/${{ github.event.inputs.tagname }})" >> $GITHUB_STEP_SUMMARY
