name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - a: a1
            aa: aa1
          - a: a2
            aa: aa2
          - a: a1
            b: b1
          - a: a2
            b: b1
          - a: a1
            b: b2
    steps:
      - name: echo
        run: echo ${{ matrix.a }} ${{ matrix.aa }} ${{ matrix.b }}



