name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [a1, a2]
        b: [b1, b2]
        c: [c1, c2]
        include:
          - a: a1
            aa: aa1
          - a: a2
            aa: aa2
          - b: b1
            bb: bb1
          - b: b2
            bb: bb2
        exclude:
          - a: a2
            b: b2
          
    steps:
      - name: echo
        run: echo ${{ matrix.a }} ${{ matrix.aa }} ${{ matrix.b }} ${{ matrix.bb }} ${{ matrix.c }}



