name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  envsetup:
    runs-on: ubuntu-latest
    outputs:
      envvar: ${{ steps.set_envvar.outputs.envvar }} # ここでoutputを設定
    steps:
      - name: Initialize ENVVAR
        id: set_envvar # このステップにIDを設定
        run: echo "::set-output name=envvar::hogehoge" # outputを設定
      - name: Echo ENVVAR
        run: echo ${{ steps.set_envvar.outputs.envvar }}

  build:
    needs: envsetup # buildジョブがenvsetupジョブに依存していることを宣言
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo ENVVAR from envsetup
        run: echo "${{ needs.envsetup.outputs.envvar }}" # envsetupジョブからoutputを参照
